const copy = {
  en: {
    navTitle: "Explore Moin", navUpload: "Upload & translate", navLive: "Haramain lessons",
    sidebarTagline: "Understanding, shared.", conceptLabel: "Design concept · September 2026",
    workspace: "Moin workspace", visualPreview: "Visual preview",
    uploadLabel: "A new way to listen", uploadTitle: "Understand every word, in your language.",
    uploadDescription: "Bring an Arabic recording. Follow the original words, read the meaning in English or French, and listen when speech is available.",
    startHere: "Start here", uploadHeading: "Add audio or video", dropTitle: "Drop your recording here",
    dropHint: "or click to choose a file from your device", dropTypes: "Audio and video files",
    uploadPrivacy: "No file is uploaded or processed in this visual preview.", processPreview: "Preview processing",
    whatYouSee: "What you will see", resultHeading: "From speech to understanding", showExample: "Show example result",
    sampleFile: "Sample teaching excerpt", sampleInfo: "Illustrative result · 00:42", ready: "Ready to explore",
    originalArabic: "Original Arabic", transcriptLabel: "Transcript", listenPreview: "▷ Listen preview",
    sampleDisclaimer: "Example content for the design preview. Translations and audio are not generated by this page.",
    processingTitle: "Processing your recording", processingDescription: "Preparing the Arabic transcript, English and French meaning, and available speech.",
    processingNote: "Visual state only — no file is sent or analyzed.", processing: "Processing",
    liveLabel: "Lessons from the two holy cities", liveTitle: "Choose a teacher. Watch the original lesson.",
    liveDescription: "Explore lessons from Makkah and Madinah, then watch the original Arabic video from YouTube.",
    chooseLocation: "From Makkah and Madinah", cityHeading: "Choose a city", streamPreviewNote: "Two lessons from YouTube",
    exploreStreams: "View lesson ↗", makkah: "Makkah", makkahSub: "Al Masjid Al Haram",
    madinah: "Madinah", madinahSub: "Al Masjid An Nabawi", teachersLabel: "Watch a lesson",
    teachersHeading: "Choose a teacher", twoTeachers: "Two teachers", lessonLabel: "Selected teacher",
    oneLesson: "One lesson available", watchLesson: "Watch lesson ↗", playOriginal: "Play the Arabic lesson",
    yourAudio: "Lesson audio", chooseLanguage: "Listen in Arabic",
    audioDescription: "The original Arabic plays in the YouTube video. Translated audio is coming later.",
    arabicAudio: "Original Arabic", sourceAudio: "Available in the video", comingLater: "Coming later",
    openYoutube: "Open on YouTube ↗", liveDisclaimer: "These are real YouTube videos. Translated audio is not available in this preview.",
    footerLine: "Meaning, made accessible.", footerPreview: "Design preview only",
    audioUnavailable: "Audio is not available in this design preview.", chosenFile: "File chosen for visual preview"
  },
  ar: {
    navTitle: "استكشف مُعين", navUpload: "ارفع ملفًا وترجمه", navLive: "دروس الحرمين",
    sidebarTagline: "لنفهم المعنى معًا.", conceptLabel: "معاينة التصميم · سبتمبر 2026",
    workspace: "مساحة مُعين", visualPreview: "معاينة التصميم",
    uploadLabel: "طريقة جديدة للاستماع", uploadTitle: "افهم الكلام بلغتك.",
    uploadDescription: "أضف تسجيلًا بالعربية، واقرأ نصه ومعناه بالإنجليزية أو الفرنسية. يمكنك الاستماع إلى الترجمة حين تتوفر.",
    startHere: "ابدأ من هنا", uploadHeading: "أضف ملفًا صوتيًا أو فيديو", dropTitle: "اسحب التسجيل إلى هنا",
    dropHint: "أو اختر ملفًا من جهازك", dropTypes: "ملفات صوت وفيديو",
    uploadPrivacy: "لا يُرفع الملف أو يُعالَج في هذه المعاينة.", processPreview: "اعرض حالة المعالجة",
    whatYouSee: "ما الذي ستراه", resultHeading: "من الكلام إلى المعنى", showExample: "اعرض مثالًا",
    sampleFile: "مقتطف تعليمي تجريبي", sampleInfo: "مثال توضيحي · 00:42", ready: "المثال جاهز",
    originalArabic: "العربية الأصلية", transcriptLabel: "النص المنطوق", listenPreview: "▷ معاينة الاستماع",
    sampleDisclaimer: "هذا مثال للتصميم. لا تُنشئ الصفحة ترجمة أو صوتًا.",
    processingTitle: "جارٍ معالجة التسجيل", processingDescription: "إعداد النص العربي والمعنى بالإنجليزية والفرنسية والصوت المتاح.",
    processingNote: "هذا عرض توضيحي فقط؛ لا يُرسل الملف ولا يُحلَّل.", processing: "جارٍ المعالجة",
    liveLabel: "دروس من مكة والمدينة", liveTitle: "اختر الشيخ وشاهد درسه.",
    liveDescription: "شاهد الدرس الأصلي بالعربية من يوتيوب. الترجمة الصوتية غير متاحة بعد.",
    chooseLocation: "من مكة والمدينة", cityHeading: "اختر المدينة", streamPreviewNote: "درسان من يوتيوب",
    exploreStreams: "عرض الدرس ↗", makkah: "مكة المكرمة", makkahSub: "المسجد الحرام",
    madinah: "المدينة المنورة", madinahSub: "المسجد النبوي", teachersLabel: "الدروس المتاحة",
    teachersHeading: "اختر الشيخ", twoTeachers: "شيخان", lessonLabel: "الشيخ المختار",
    oneLesson: "درس واحد متاح", watchLesson: "شاهد الدرس ↗", playOriginal: "شغّل الدرس بالعربية",
    yourAudio: "صوت الدرس", chooseLanguage: "استمع بالعربية",
    audioDescription: "الصوت العربي متاح في الفيديو. سنضيف الترجمة الصوتية لاحقًا.",
    arabicAudio: "العربية الأصلية", sourceAudio: "متاح في الفيديو", comingLater: "غير متاح بعد",
    openYoutube: "افتح في يوتيوب ↗", liveDisclaimer: "هذان درسان حقيقيان من يوتيوب. الترجمة الصوتية غير متاحة بعد.",
    footerLine: "المعنى أقرب إلى الجميع.", footerPreview: "معاينة تصميمية فقط",
    audioUnavailable: "الصوت غير متاح في هذه المعاينة.", chosenFile: "ملف مختار لمعاينة التصميم"
  }
};

const teachers = [
  {
    id: "shuwaier", city: "makkah", videoId: "I7DBkkHaMdM",
    image: "./assets/shuwaier-youtube.jpg",
    name: {en: "Sheikh Abdulsalam Al-Shuwaier", ar: "الشيخ عبدالسلام الشويعر"},
    lesson: {en: "The Important Lessons for the Ummah · Lesson 1", ar: "شرح الدروس المهمة لعامة الأمة · الدرس 1"},
    source: {en: "Haram Mosque Lessons · YouTube", ar: "دروس المسجد الحرام · يوتيوب"}
  },
  {
    id: "badr", city: "madinah", videoId: "np7VbEJdw7M",
    image: "./assets/badr-youtube.jpg",
    name: {en: "Sheikh Abdulrazzaq Al-Badr", ar: "الشيخ عبدالرزاق البدر"},
    lesson: {en: "Tafsir al-Sa'di", ar: "تفسير السعدي"},
    source: {en: "Prophet's Mosque Lessons · YouTube", ar: "دروس المسجد النبوي · يوتيوب"}
  }
];

let locale = "en";
let page = "upload";
let city = "makkah";
let teacherId = "shuwaier";
let resultState = "example";
let previewFileName = "";

function t(key) { return copy[locale][key]; }

function setLocale(next) {
  locale = next;
  document.documentElement.lang = next;
  document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
  document.title = next === "ar" ? "مُعين — معاينة التصميم" : "Moin — Design preview";
  document.querySelectorAll("[data-i18n]").forEach(element => {
    element.textContent = t(element.dataset.i18n);
  });
  document.querySelectorAll("[data-locale]").forEach(button => {
    button.setAttribute("aria-pressed", String(button.dataset.locale === next));
  });
  document.querySelector(".sidebar").setAttribute("aria-label", next === "ar" ? "التنقل الرئيسي" : "Primary navigation");
  document.querySelector(".primary-nav").setAttribute("aria-label", next === "ar" ? "الصفحات الرئيسية" : "Main pages");
  document.querySelector(".locale-switch").setAttribute("aria-label", next === "ar" ? "لغة الواجهة" : "Interface language");
  document.querySelector(".city-grid").setAttribute("aria-label", next === "ar" ? "اختر المدينة" : "Choose city");
  document.querySelector(".teacher-grid").setAttribute("aria-label", next === "ar" ? "اختر الشيخ" : "Choose teacher");
  document.querySelector("#media-file").setAttribute("aria-label", next === "ar" ? "اختر ملفًا صوتيًا أو فيديو" : "Choose audio or video file");
  if (previewFileName) document.querySelector("#drop-title").textContent = previewFileName;
  updatePageLabels();
  renderTeachers();
  renderLesson();
  if (resultState === "processing") updateProcessingLabels();
}

function updatePageLabels() {
  document.querySelector("#breadcrumb-current").textContent = page === "upload" ? t("navUpload") : t("navLive");
  document.querySelectorAll(".nav-item").forEach(button => {
    const active = button.dataset.page === page;
    button.classList.toggle("is-active", active);
    if (active) button.setAttribute("aria-current", "page");
    else button.removeAttribute("aria-current");
  });
}

function showPage(next) {
  page = next;
  document.querySelectorAll(".page").forEach(section => {
    const active = section.id === `${next}-page`;
    section.hidden = !active;
    section.classList.toggle("is-visible", active);
  });
  updatePageLabels();
  history.replaceState(null, "", `#${next}`);
  window.scrollTo({top: 0, behavior: "auto"});
}

function selectedTeacher() { return teachers.find(teacher => teacher.id === teacherId); }

function renderTeachers() {
  const grid = document.querySelector("#teacher-grid");
  grid.replaceChildren();
  teachers.forEach(teacher => {
    const card = document.createElement("button");
    card.type = "button";
    card.className = `teacher-card${teacher.id === teacherId ? " is-selected" : ""}`;
    card.setAttribute("aria-pressed", String(teacher.id === teacherId));
    const portrait = document.createElement("span");
    portrait.className = `teacher-portrait teacher-portrait-${teacher.id}`;
    portrait.setAttribute("aria-hidden", "true");
    const info = document.createElement("span");
    info.className = "teacher-card-info";
    const location = document.createElement("small");
    location.textContent = teacher.city === "makkah" ? t("makkah") : t("madinah");
    const name = document.createElement("strong");
    name.textContent = teacher.name[locale];
    const lesson = document.createElement("span");
    lesson.textContent = teacher.lesson[locale];
    info.append(location, name, lesson);
    const arrow = document.createElement("span");
    arrow.className = "teacher-card-arrow";
    arrow.setAttribute("aria-hidden", "true");
    arrow.textContent = "↗";
    card.append(portrait, info, arrow);
    card.addEventListener("click", () => selectTeacher(teacher.id, true));
    grid.append(card);
  });
}

function renderLesson() {
  const teacher = selectedTeacher();
  document.querySelector("#watch-heading").textContent = teacher.name[locale];
  document.querySelector("#lesson-title").textContent = teacher.lesson[locale];
  document.querySelector("#lesson-source").textContent = teacher.source[locale];
  document.querySelector("#lesson-thumb").src = teacher.image;
  document.querySelector("#video-cover-image").src = teacher.image;
  document.querySelector("#youtube-link").href = `https://www.youtube.com/watch?v=${teacher.videoId}`;
  document.querySelector("#lesson-video").title = `${teacher.name[locale]} — ${teacher.lesson[locale]}`;
  document.querySelectorAll("[data-city]").forEach(item => {
    const active = item.dataset.city === city;
    item.classList.toggle("is-selected", active);
    item.setAttribute("aria-pressed", String(active));
  });
}

function selectTeacher(id, scroll) {
  if (teacherId !== id) {
    const video = document.querySelector("#lesson-video");
    video.removeAttribute("src");
    video.hidden = true;
    document.querySelector("#video-cover").hidden = false;
  }
  teacherId = id;
  city = selectedTeacher().city;
  renderTeachers();
  renderLesson();
  if (scroll) document.querySelector("#lesson-section").scrollIntoView({behavior: "smooth", block: "start"});
}

function playLesson() {
  const video = document.querySelector("#lesson-video");
  video.src = `https://www.youtube.com/embed/${selectedTeacher().videoId}?autoplay=1&rel=0`;
  document.querySelector("#video-cover").hidden = true;
  video.hidden = false;
}

function showProcessing() {
  resultState = "processing";
  document.querySelector("#processing-state").hidden = false;
  document.querySelector("#sample-result").hidden = true;
  updateProcessingLabels();
  document.querySelector("#result-heading").scrollIntoView({behavior: "smooth", block: "start"});
}

function updateProcessingLabels() {
  const status = document.querySelector("#result-status");
  status.classList.add("is-processing");
  status.lastElementChild.textContent = t("processing");
  document.querySelector("#result-file-name").textContent = previewFileName || t("sampleFile");
  document.querySelector("#result-file-name").dir = "auto";
  document.querySelector("#result-file-name").nextElementSibling.textContent = t("chosenFile");
}

function showExample() {
  resultState = "example";
  document.querySelector("#processing-state").hidden = true;
  document.querySelector("#sample-result").hidden = false;
  const status = document.querySelector("#result-status");
  status.classList.remove("is-processing");
  status.lastElementChild.textContent = t("ready");
  document.querySelector("#result-file-name").textContent = t("sampleFile");
  document.querySelector("#result-file-name").nextElementSibling.textContent = t("sampleInfo");
}

function showPreviewNotice() {
  let note = document.querySelector("#preview-notice");
  if (!note) {
    note = document.createElement("div");
    note.id = "preview-notice";
    note.className = "preview-notice";
    note.setAttribute("role", "status");
    document.body.append(note);
  }
  note.textContent = t("audioUnavailable");
  note.classList.add("is-shown");
  clearTimeout(showPreviewNotice.timeout);
  showPreviewNotice.timeout = setTimeout(() => note.classList.remove("is-shown"), 3200);
}

document.querySelectorAll("[data-locale]").forEach(button => button.addEventListener("click", () => setLocale(button.dataset.locale)));
document.querySelectorAll("[data-page]").forEach(button => button.addEventListener("click", () => showPage(button.dataset.page)));
document.querySelectorAll("[data-city]").forEach(button => button.addEventListener("click", () => {
  const teacher = teachers.find(item => item.city === button.dataset.city);
  selectTeacher(teacher.id, true);
}));
document.querySelector("#lesson-row").addEventListener("click", playLesson);
document.querySelector("#video-cover").addEventListener("click", playLesson);
document.querySelector("#preview-process").addEventListener("click", showProcessing);
document.querySelector("#example-result").addEventListener("click", showExample);
document.querySelector("#media-file").addEventListener("change", event => {
  const file = event.target.files[0];
  if (file) {
    previewFileName = file.name;
    document.querySelector("#drop-title").textContent = file.name;
  }
});
document.querySelectorAll(".listen-button,.sample-play").forEach(button => button.addEventListener("click", showPreviewNotice));
const dropzone = document.querySelector("#dropzone");
dropzone.addEventListener("dragover", event => { event.preventDefault(); dropzone.classList.add("is-dragging"); });
dropzone.addEventListener("dragleave", () => dropzone.classList.remove("is-dragging"));
dropzone.addEventListener("drop", event => {
  event.preventDefault();
  dropzone.classList.remove("is-dragging");
  const file = event.dataTransfer.files[0];
  if (file) {
    previewFileName = file.name;
    document.querySelector("#drop-title").textContent = file.name;
  }
});
setLocale("en");
showPage(location.hash === "#live" ? "live" : "upload");
